---

kind: pipeline
name: skafossdk

steps:
  - name: publish_stable
    image: plugins/pypi
    settings:
      version: "${DRONE_TAG}"
      username:
        from_secret: pypi_username
      password:
        from_secret: pypi_password
      distribution:
        - sdist
        - bdist_wheel
      skip_build: false
    when:
      status:
        - success
      event:
        - tag
      ref:
        - refs/tags/*
  - name: publish_dev
    image: plugins/pypi
    settings:
      build_number: "${DRONE_BUILD_NUMBER}"
      repository: "https://test.pypi.org/legacy/"
      username: ""
      password: ""
      distribution:
        - sdist
        - bdist_wheel
      skip_build: false
    when:
      status:
        - success
      event:
        - push
      branch:
        - master
  - name: slack
    image: plugins/slack
    settings:
      channel: builds
      username: Drone
      webhook:
        from_secret: slack_webhook
    when:
      status:
        - success
        - failure
